[package]
name = "pywr-next"
version = "0.1.0"
authors = ["James Tomlinson <tomo.bbe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
thiserror = "1.0"
chrono = "0.4"
ndarray = "0.13"
float-cmp = "0.8.0"
clp-sys = { path = "./clp-sys" }

[dependencies.pyo3]
version = "*"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[lib]
name = "pywr"
crate-type = ["cdylib"]

[package.metadata.maturin]
requires-dist = ["pydantic"]

[workspace]
members = [
    "clp-sys",
]
